(eval-when (:compile-toplevel :load-toplevel :execute)
  (defun symbol-char-p (c)
    (and (char>= c #\!) (char<= c #\`)))
  (defvar *supported-types* (make-hash-table))
  (defvar *functions-table* (make-hash-table))
  (defvar *data-types* (make-hash-table)))

(defun prerequisite-setup ()
  (setf (gethash :number *supported-types*) (list 'parse-integer 'digit-char-p))
  (setf (gethash :function *supported-types*) (list 'read-from-string 'symbol-char-p))
  (setf (gethash :region *supported-types*) (list 'intern 'alpha-char-p))
  (setf (gethash :identifier *supported-types*) (list 'intern 'alpha-char-p))
  (setf (gethash 'int *data-types*) :number))
